blog/urls.py
from django.urls import path
from . import views



app_name = 'blog'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='blog_about'),
    path('create/', views.createBlog , name='createBlog'),
    path('<int:post_id>/show/', views.show , name='show'),
    path('<int:post_id>/delete/', views.deleteBlog , name='deleteBlog'),
    path('<int:post_id>/edit/', views.editBlog , name='editBlog'),
    path('<int:post_id>/update/', views.updateBlog , name='updateBlog'),

]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from blog import views as blog_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.home , name='home'),
    path('blog/',include('blog.urls')),
    path('blog/',include('blog.urls')),
    path('users/',include('users.urls')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

from django.urls import reverse, reverse_lazy, resolve

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout , name='logout'),
    path('dashboard/', views.dashboard , name='dashboard'),
    path('<int:user_id>/profile/', views.profile , name='profile'),
    path('myposts/', views.myposts , name='myposts'),
]

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url "blog:home" %}">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url "blog:home" %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "blog:blog_about" %}">About</a>
      </li>


      {% if user.is_authenticated %}
        <li class="nav-item mr-3">
          <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
          <i class="fas fa-sign-out-alt"></i> Logout
          </a>
          <li class="nav-item">
          <a class="nav-link" href="{% url "users:profile" user.id %}">Profile</a>
          </li>
           <form  method="post" id="logout" action="{% url "users:logout" %}">
              {% csrf_token %}
              <input type="hidden">
          </form>
       </li>

       <li class="nav-item">
        <a class="nav-link" href="{% url "users:dashboard" %}">Dashboard</a>
       </li>

       <li class="nav-item">
        <a class="nav-link" href="{% url "blog:createBlog" %}">Create Post</a>
       </li>
      {% else %}
           <li class="nav-item">
            <a class="nav-link" href="{% url "users:register" %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "users:login" %}">Login</a>
          </li>
      {% endif %}




    </ul>
  </div>
</nav>

templates/partials/_sidebar.html
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                {% if user.is_authenticated %}
                   <li class="list-group-item list-group-item-light"><a href="{% url "users:profile" user.id %}">Profile</a></li>

                  <li class="list-group-item list-group-item-light"><a href="{% url "users:myposts"%}">My Posts</a></li>

                {% endif %}
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>