blog/urls.py
from django.urls import path
from . import views



app_name = 'blog'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='blog_about'),
    path('create/', views.createBlog , name='createBlog'),
    path('<int:post_id>/show/', views.show , name='show'),
    path('<int:post_id>/delete/', views.deleteBlog , name='deleteBlog'),
    path('<int:post_id>/edit/', views.editBlog , name='editBlog'),
    path('<int:post_id>/update/', views.updateBlog , name='updateBlog'),

]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from blog import views as blog_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.home , name='home'),
    path('blog/',include('blog.urls')),
    path('blog/',include('blog.urls')),
    path('users/',include('users.urls')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:100] + '.....'

    def pub_date_pretty(self):
        return self.date_posted.strftime('%b %e %Y')

  #   def get_absolute_url(self):
		# return reverse('post-detail', kwargs={'pk': self.pk})

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.core.paginator import Paginator

from .models import Post

# Create your views here.

def createBlog(request):
	if request.method == 'POST':
		title = request.POST['title']
		content = request.POST['content']
		if title and content:
			author = request.user;
			post = Post(title=title,content=content,author=author)
			post.save()
			messages.success(request,'Post Created SuccessFully')
			return redirect('users:myposts')
		else:
			messages.warning(request,'Filed Must Be Filled')
			return redirect('blog:createBlog')
	else:
		return render(request,'blog/create.html')


def home(request):
	posts = Post.objects.all()
	paginator = Paginator(posts, 4)
	page = request.GET.get('page')
	posts = paginator.get_page(page)
	return render(request,'blog/home.html',{'posts' : posts})

def show(request,post_id):
	postById = get_object_or_404(Post,pk=post_id)
	return render(request,'blog/show.html',{'post' : postById})


def deleteBlog(request,post_id):
	if request.method == 'POST':
		author_id = get_object_or_404(Post,pk=post_id).author_id
		current_user = request.user.id
		if author_id == current_user:
			post = Post.objects.filter(pk = post_id)
			post.delete()
			messages.success(request,'Post Deleted SuccessFully')
			return redirect('users:dashboard')
	else:
		messages.warning(request,'You Dont Have Permission')
		return redirect('blog:show',post_id = post_id)

def editBlog(request,post_id):
	author_id = get_object_or_404(Post,pk=post_id).author_id
	if request.user.id == author_id:
		post = get_object_or_404(Post,pk=post_id)
		#return HttpResponse(post)
		return render(request , 'blog/edit.html',{'post' : post})
	else:
		messages.warning(request,'You Dont Have Permission')
		return redirect('blog:show',post_id = post_id)


def updateBlog(request,post_id):
	if request.method == 'POST':
		title = request.POST['title']
		content = request.POST['content']
		if title and content:
			post = get_object_or_404(Post,pk=post_id)
			post.title = title
			post.content = content
			post.save()
			messages.success(request,'Post Updated SuccessFully')
			return redirect('blog:show',post_id = post_id)
		else:
			messages.warning(request,'Filed Must Be Filled')
			return redirect('blog:editBlog',post_id = post_id)
	else:
		messages.warning(request,'You Dont Have Permission')
		return redirect('blog:editBlog',post_id = post_id)




def about(request):
	return render(request,'blog/about.html')

templates/blog/about.html
{% extends "base.html" %}
{% block title %}
   About
{% endblock title %}


{% block content %}

  	<div class="col-md-8">
  		<h1>About</h1>
  	</div>

  	<div class="col-md-4">
  		{% include 'partials/_sidebar.html' %}
  	</div>

{% endblock content %}

templates/blog/create.html
{% extends "base.html" %}
{% block title %}
   Create Post
{% endblock title %}


{% block content %}

  	<div class="col-md-8 mt-3">
  		<h3>Create Post</h3>
		<form action="{% url "blog:createBlog" %}" method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label>Title</label>
				<input type="text" name="title"  class="form-control">
			</div>
			<div class="form-group">
				<label>Content</label>
				<textarea name="content"  cols="30" rows="10" class="form-control">

				</textarea>
			</div>

			<div class="group">
				<input type="submit" value="Save" class="btn btn-dark btn-block">
			</div>
		</form>
  	</div>

  	<div class="col-md-4">
  		{% include 'partials/_sidebar.html' %}
  	</div>

{% endblock content %}

templates/blog/edit.html
{% extends "base.html" %}
{% block title %}
   {{post.title}}
{% endblock title %}


{% block content %}

  	<div class="col-md-8 mt-3">
  		<h3>Update Post: <strong>{{post.title}}</strong></h3>
		<form action="{% url "blog:updateBlog" post.id %}" method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label>Title</label>
				<input type="text" name="title" value="{{post.title}}" class="form-control">
			</div>
			<div class="form-group">
				<label>Content</label>
				<textarea name="content" id="" cols="30" rows="10" class="form-control">
					{{post.content}}
				</textarea>
			</div>

			<div class="group">
				<input type="submit" value="Update" class="btn btn-dark btn-block">
			</div>
		</form>
  	</div>

  	<div class="col-md-4">
  		{% include 'partials/_sidebar.html' %}
  	</div>

{% endblock content %}

templates/blog/home.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock title %}



{% block content %}

  <div class="col-8">
	  	{% if posts %}
	    {% for post in posts %}
	          <div class="mt-4">
	          	 <article class="media content-section">
			          <img height="100" class="rounded-circle" src="{{ post.author.profile.image.url }}">
			        <div class="media-body">
			            <div class="article-metadata">
			              <a class="mr-2" href="#">{{ post.author }}</a>
			              <small class="text-muted">{{ post.pub_date_pretty }}</small>
			            </div>
			            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
			            <p class="article-content">{{ post.summary }}</p>
			            <a href="{% url "blog:show" post.id %}" class="float-right btn-link">Read More</a>
					</div>

				</article>
	          </div>
	    {% endfor %}
	  {% else %}
	     <p>Nothing To Show</p>
	  {% endif %}

      <div class="mx-auto">

          {% if posts.has_other_pages %}

            <ul class="pagination">
               {% if posts.has_previous %}
                  <li class="page-item">
                    <a href="?page={{posts.previous_page_number}}" class="page-link">&laquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&laquo;</a>
                   </li>
               {% endif %}
               {% for i in posts.paginator.page_range %}
                 {% if posts.number == i %}

                  <li class="page-item active">
                    <a class="page-link">{{i}}</a>
                  </li>
                 {% else %}
                      <li class="page-item">
                        <a href="?page={{i}}" class="page-link">{{i}}</a>
                      </li>
                 {% endif %}
               {% endfor %}
               {% if posts.has_next %}
                  <li class="page-item">
                    <a href="?page={{posts.next_page_number}}" class="page-link">&raquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&raquo;</a>
                   </li>
               {% endif %}
            </ul>

          {% else %}

          {% endif %}

  	  </div>


  </div>


  <div class="col-md-4">
  		{% include 'partials/_sidebar.html' %}
  	</div>

{% endblock content %}

templates/blog/show.html
{% extends "base.html" %}
{% block title %}
   {{post.title}}
{% endblock title %}


{% block content %}

  	<div class="col-md-8 mt-3">
  		 <img class="rounded-circle" style="width: 5rem;"  src="{{user.profile.image.url}}">
  		<div class="card">

		  <div class="card-body">
		    <h5 class="card-title">{{post.title}}</h5>
		    <p class="card-text">{{post.content}}</p>
		    {% if user.id == post.author_id %}

                <a href="{% url "blog:editBlog" post.id %}" class="btn btn-info float-left">Edit</a>
			    <span class="float-right">
			    	<form action="{% url "blog:deleteBlog" post.id %}" method="post">
					    {% csrf_token %}
					    <input type="hidden" name="_method" value="delete">
					    <input class="btn btn-danger" type="submit" value="Delete">
					</form>
			    </span>

		    {% endif %}
		  </div>
		</div>
  	</div>

  	<div class="col-md-4">
  		{% include 'partials/_sidebar.html' %}
  	</div>

{% endblock content %}